name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_safe:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy
      run: cargo clippy --no-deps --all-targets
    - name: Run tests
      run: cargo test --verbose

  build_unsafe:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build
       run: cargo build --verbose --features unsafe
     - name: Run Clippy
       run: cargo clippy --no-deps --all-targets --features unsafe
     - name: Run tests
       run: cargo test --verbose --features unsafe

   
